### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by dehghani-mehdi** [nuchi/firefox-quantum-userchromejs#1]
Hi,

I know it's not a plugin, but any help here would be great.

I followed the instruction, but the js code (I simply added an `alert()`) doen't work. any idea why?

Thanks.

**Comment by nuchi** [comment]
Some commenters in [this reddit thread](https://www.reddit.com/r/firefox/comments/7f6kc4/floating_scrollbar_finally_possible_in_firefox_57/) noticed that changes don't take effect until you clear your cache. Could that be it?

**Comment by dehghani-mehdi** [comment]
Thanks for the support, I cleared the cache, but still doesn't work.

I deleted all content of `userChrome.js` file and added just an `alert()`, is that okay?

**Comment by nuchi** [comment]
In that case I don't know. You could try asking for help on that reddit
thread — looks like people have had success with it there and might be able
to help.

**Comment by dehghani-mehdi** [comment]
Thanks man, so I closed the issue.
