### ISSUE TITLE
Link to Bugzilla Bug?

### ISSUE THREAD

**Issue by tomrittervg** [nuchi/firefox-quantum-userchromejs#10]
I stumbled across this trying to figure out how people were injecting Javascript without using general.config.filename (https://bugzilla.mozilla.org/show_bug.cgi?id=1573622 ). Very inventive.

Anyway, is https://bugzilla.mozilla.org/show_bug.cgi?id=1016361#c21 the fullscreen behavior you desire?

**Comment by nuchi** [comment]
> Anyway, is https://bugzilla.mozilla.org/show_bug.cgi?id=1016361#c21 the fullscreen behavior you desire?

I mean, yeah, but I'm just one person and I assume people are using this method for lots of things other than what I originally made it for. So I wouldn't expect all that noise in your telemetry (sorry about that, by the way! unintended side effect) to go away if the fullscreen thing is resolved.

**Comment by tomrittervg** [comment]
No worry about the Telemetry - thanks for documenting what you did somewhere public so I could find it!

And yeah, I'm certain this is being used by the majority of people for something else; but eventually we hope to deprecate/remove this trick and I wanted to at least make you aware of what I hope will be a forthcoming solution to at least your use case.

**Comment by nuchi** [comment]
Thanks for letting me know. Do you happen to have any links to issue trackers for any changes which would stop the method in this repo from working?
