### ISSUE TITLE
Broken in Firefox 70 beta

### ISSUE THREAD

**Issue by kapitainsky** [nuchi/firefox-quantum-userchromejs#11]
Looks like it stopped working for next Firefox release

**Comment by nuchi** [comment]
Works for me on 70.0b7. Can you verify that you're on the latest commit, and that your .css and .xml files are unmodified?

If you replace the contents of your .js file with `console.log('test');` and open the browser console (cmd-shift-J on mac), do you see the test message?

**Comment by kapitainsky** [comment]
Indeed works. I did fresh install and forgot to switch toolkit.legacyUserProfileCustomizations.stylesheets to true.  

BTW - reading this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1016361#c21) on Mozilla site  where even your solution in mentioned it seems that in the near future such customization will be gone.

**Comment by nuchi** [comment]
Glad to hear it! Leaving this open for now as a reminder to myself to add some troubleshooting information.
