### ISSUE TITLE
userchrome doesn't install on Firefox 59.0.2

### ISSUE THREAD

**Issue by quinton-ashley** [nuchi/firefox-quantum-userchromejs#4]

**Comment by nuchi** [comment]
Hi there! Thanks for the report. Could you please describe which operating system you're using, your installation process, and what you saw that let you to conclude that the installation failed?

Screenshots would be useful if you can provide any.

**Comment by quinton-ashley** [comment]
Sorry for the late response, I was either on macOS High Sierra or Windows 10.  I was confused about what userchrome did and found Tampermonkey was what I needed.
