### ISSUE TITLE
Breaks "List all tabs" button?

### ISSUE THREAD

**Issue by meribold** [nuchi/firefox-quantum-userchromejs#7]
I think this code started to break the "List all tabs" button at some point—maybe since Firefox 62. There simply isn't any response when I click the button. I edited `userChrome.css` to use `toolbarbutton#feed-button` instead of `toolbarbutton#alltabs-button` and that seems to fix it.

I don't really know how to debug this any further.

**Comment by nuchi** [comment]
Thanks for the report! I've pushed a fix. (I don't know whether your fix would have introduced other errors on top of fixing the existing problem.)

If it's still broken for you, please re-open this issue.
