### ISSUE TITLE
Ignore cache

### ISSUE THREAD

**Issue by Kyuuhachi** [nuchi/firefox-quantum-userchromejs#8]
It seems a recent FF version changed `loadSubScript` so it uses a cache, which makes modifying userChrome.js a bit inconvenient. The `loadSubScript` line should be changed to `Services.scriptloader.loadSubScriptWithOptions(makeRelativePathURI("userChrome.js"), {target: window, ignoreCache: true});`, but I'm too lazy to make a proper pull request.

**Comment by pm64** [comment]
As of 2/2019, firefox-quantum-userchromejs appears to no longer work.

**Comment by Kyuuhachi** [comment]
Really? I have a WIP plugin which depends heavily on this functionality, so that could be bad. I'll investigate later.

**Comment by Kyuuhachi** [comment]
Nope, works fine for me (with FF 65, on Arch).

**Comment by pm64** [comment]
@Caagr98, please let me know if you find differently. I tried for some time but was constantly thwarted by FF security.

**Comment by Kyuuhachi** [comment]
I had no issues at all, so that's pretty weird.

**Comment by pm64** [comment]
I'm baffled. I tried testing by adding an alert("foo") to userChrome.js, which caused a security error to display in the console. Then I tried logging a message to the console, which also failed. Maybe I just need to read up on this a little more. Thank you for this encouraging information.

**Comment by nuchi** [comment]
works for me on version 66 beta. please open a new issue

**Comment by nuchi** [comment]
@Caagr98 — fixed in [the latest commit](https://github.com/nuchi/firefox-quantum-userchromejs/commit/72e53e65dfedebe5707f25d511c8b8967e5faf00). Thanks for the report and the fix suggestion.
